version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    container_name: "es-container"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    container_name: "kibana-container"
    ports: 
      - 5601:5601
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
  filebeat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "filebeat-container"
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    volumes:
      - ./fdata:/usr/share/filebeat/data
    


